baseURL = "https://bingersoda.github.io/tmei/"
languageCode = "en-us"
title = "Ting Mei"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  description = "Writer, editor, and developer."

[markup.goldmark.parser.attribute]
  block = true
  title = true

[markup.goldmark.renderer]
unsafe = true